"""Exact Korean herb-name search bridges from cited public reference indexes.

Facts extracted from 70 visible NIKOM index pages (691 total rows) on 2026-09-07.
Minerals, prescriptions, unresolved placeholders and recognized suspect spellings
are excluded; no unsupported spelling correction is made. These are source-
reported taxa, not accepted-taxonomy reconciliation or complete pharmacopoeial
origins. No efficacy or batch-composition assertions are imported. Source HTML
and checksum receipts remain under runtime/discovery/downloads. Reference-site
content licences are unspecified; no open-content licence is asserted.
"""

from __future__ import annotations

import re
import unicodedata
from copy import deepcopy

_NIKOM_URL = "https://nikom.or.kr/kmmb/module/herbs/index.do"
_LICENSE = "unspecified; factual reference index only"
_NIKOM_FACTS = [
    ('가바쌀', 'Oryza Sativa', 1),
    ('가자', 'Terminalia chebula', 1),
    ('갈근', 'Pueraria lobata', 1),
    ('갈용', 'Pueraria lobata', 1),
    ('갈화', 'Pueraria lobata', 1),
    ('감국', 'Chrysanthemum indicum', 1),
    ('감송향', 'Nardostachys chinensis', 1),
    ('감수', 'Euphorbia kansui', 1),
    ('감초', 'Glycyrrhiza uralensis', 1),
    ('강향', 'Dalbergia odorifera', 2),
    ('강활', 'Ostericum koreanum', 2),
    ('강황', 'Curcuma longa', 2),
    ('개자', 'Brassica juncea', 2),
    ('건강', 'Zingiber officinale', 2),
    ('건율', 'Castanea crenata', 2),
    ('검인', 'Euryale ferox', 2),
    ('견우자', 'Pharbitis nil', 2),
    ('결명자', 'Cassia tora', 2),
    ('경포부자', 'Aconitum carmichaeli', 2),
    ('계내금', 'Gallus gallus', 3),
    ('계지', 'Cinnamomum cassia', 3),
    ('계혈등', 'Spatholobus suberectus', 3),
    ('고과', 'Momordica charantia', 3),
    ('고근', 'Zizania caduciflora', 3),
    ('고량강', 'Alpinia officinarum', 3),
    ('고련피', 'Melia azedarach', 3),
    ('고목', 'Picrasma quassioides', 3),
    ('고본', 'Angelica tenuissima', 3),
    ('고삼', 'Sophora flavescens', 4),
    ('고장초', 'Zizania latifolia', 4),
    ('고채', 'Ixeris dentata', 4),
    ('고초엽', 'Capsicum annuum', 4),
    ('곡기생', 'Viscum album', 4),
    ('곡아', 'Oryza sativa', 4),
    ('곡정초', 'Eriocaulon sieboldianum', 4),
    ('곤드레', 'Cirsium setidens', 4),
    ('골담초근', 'Caragana sinica', 4),
    ('골쇄보', 'Drynaria fortunei', 4),
    ('과체', 'Cucumis melo', 5),
    ('곽향', 'Agastache rugosa', 5),
    ('관동화', 'Tussilago farfara', 5),
    ('관중', 'Dryopteris crassirhizoma', 5),
    ('괄루근', 'Trichosanthes kirilowii', 5),
    ('괄루인', 'Trichosanthes kirilowii', 5),
    ('광곽향', 'Pogostemon cablin', 5),
    ('광금전초', 'Desmodium styracifolium', 5),
    ('괴각', 'Sophora japonica', 5),
    ('괴화', 'Sophora japonica', 5),
    ('교맥', 'Fagopyrum esculentum', 6),
    ('교이', 'Oryza sativa', 6),
    ('구골엽', 'Ilex cornuta', 6),
    ('구기자', 'Lycium chinense', 6),
    ('구맥', 'Dianthus chinensis', 6),
    ('구인', 'Allolobophora caliginosa', 6),
    ('구자', 'Allium tuberosum', 6),
    ('구절초', 'Chrysanthemum zawadskii', 6),
    ('구척', 'Cibotium barometz', 6),
    ('구판', 'Chinemys reevesii', 6),
    ('구피마', 'Broussonetia kazinoki', 7),
    ('국거', 'Cichorium intybus', 7),
    ('국우', 'Helianthus tuberosus', 7),
    ('국화', 'Chrysanthemum indicum', 7),
    ('권백', 'Selaginella tamariscina', 7),
    ('권삼', 'Bistorta manshuriensis', 7),
    ('궐', 'Pteridium aquilinum', 7),
    ('귀전우', 'Euonymus alatus', 7),
    ('귀판', 'Chinemys reevesii', 7),
    ('귤핵', 'Citrus unshiu', 7),
    ('그라비올라', 'Annona muricata', 8),
    ('금앵자', 'Rosa laevigata', 8),
    ('금은화', 'Lonicera japonica', 8),
    ('금전초', 'Lysimachia christinae', 8),
    ('급성자', 'Impatiens balsamina', 8),
    ('길초', 'Valeriana fauriei', 8),
    ('길초근', 'Valeriana fauriei', 8),
    ('남사등', 'Celastrus orbiculatus', 8),
    ('낭독', 'Euphorbia fischeriana', 8),
    ('내복', 'Raphanus sativus', 9),
    ('내복자', 'Raphanus sativus', 9),
    ('노근', 'Phragmites communis', 9),
    ('노로통', 'Liquidambar formosana', 9),
    ('노봉방', 'Polistes mandarinus', 9),
    ('녹각', 'Cervus nippon', 9),
    ('녹각교', 'Cervus nippon', 9),
    ('녹각채', 'Codium fragile', 9),
    ('녹용', 'Cervus nippon', 10),
    ('녹제초', 'Pyrola japonica', 10),
    ('녹차잎', 'Camellia sinensis', 10),
    ('누고', 'Gryllotalpa orientalis', 10),
    ('능소화', 'Campsis grandiflora', 10),
    ('능실', 'Trapa japonica', 10),
    ('다미아나', 'Turnera diffusa', 10),
    ('다엽', 'Camellia sinensis', 11),
    ('단삼', 'Salvia miltiorrhiza', 11),
    ('담죽엽', 'Lophatherum gracile', 11),
    ('당귀', 'Angelica gigas', 11),
    ('당삼', 'Codonopsis tangshen', 11),
    ('당약', 'Swertia japonica', 11),
    ('대가', 'Solanum melongena', 11),
    ('대계근', 'Cirsium japonicum', 11),
    ('대계초', 'Cirsium japonicum', 11),
    ('대극', 'Euphorbia pekinensis', 11),
    ('대두황권', 'Glycine max', 12),
    ('대복피', 'Areca catechu', 12),
    ('대청엽', 'Polygonum tinctorium', 12),
    ('대추', 'Zizyphus jujuba', 12),
    ('대풍자', 'Hydnocarpus anthelmintica', 12),
    ('대황', 'Rheum palmatum', 12),
    ('도경', 'Inula japonica', 12),
    ('도두', 'Canavalia gladiata', 12),
    ('도인', 'Prunus persica', 12),
    ('독활', 'Aralia continentalis', 13),
    ('동규자', 'Malva verticillata', 13),
    ('동충하초', 'Cordyceps militaris', 13),
    ('동풍채', 'Aster scaber', 13),
    ('두견화근', 'Rhododendron mucronulatum', 13),
    ('두송실', 'Juniperus rigida', 13),
    ('두시', 'Glycine max', 13),
    ('두충', 'Eucommia ulmoides', 13),
    ('등심초', 'Juncus effusus', 14),
    ('등피', 'Citrus aurantium', 14),
    ('등합환', 'Celastrus orbiculatus', 14),
    ('라벤더', 'Lavandula angustifolia', 14),
    ('로즈마리', 'Rosmarinus officinalis', 14),
    ('마가목', 'Sorbus commixta', 14),
    ('마발', 'Lasiosphaera nipponica', 14),
    ('마인', 'Cannabis sativa', 14),
    ('마전자', 'Strychnos nux-vomica', 14),
    ('마치현', 'Portulaca oleracea', 14),
    ('마편초', 'Verbena officinalis', 15),
    ('마황', 'Ephedra sinica', 15),
    ('마황근', 'Ephedra sinica', 15),
    ('만청', 'Raphanus sativus', 15),
    ('만형자', 'Vitex rotundifolia', 15),
    ('매괴화', 'Rosa rugosa', 15),
    ('맥문동', 'Liriope platyphylla', 15),
    ('맥아', 'Hordeum vulgare', 15),
    ('맹충', 'Tabanus bivittatus', 15),
    ('면실자', 'Gossypium nanking', 16),
    ('명월초', 'Gynura procumbens', 16),
    ('모과', 'Chaenomeles speciosa', 16),
    ('모과', 'Chaenomeles sinensis', 16),
    ('모근', 'Imperata cylindrica', 16),
    ('모려', 'Ostrea gigas', 16),
    ('모링가잎', 'Moringa Oleifera', 16),
    ('목단피', 'Paeonia suffruticosa', 16),
    ('목두채', 'Aralia elata', 16),
    ('목방기', 'Cocculus trilobus', 17),
    ('목별자', 'Momordica cochinchinensis', 17),
    ('목이', 'Auricularia auricula-judae', 17),
    ('목적', 'Equisetum hyemale', 17),
    ('목천료', 'Actinidia polygama', 17),
    ('목천료자', 'Actinidia polygama', 17),
    ('목통', 'Akebia quinata', 17),
    ('목향', 'Aucklandia lappa', 17),
    ('몰로키아', 'Corchorus olitorius', 17),
    ('몰약', 'Commiphora myrrha', 17),
    ('무화과', 'Ficus carica', 18),
    ('문합', 'Meretrix meretrix', 18),
    ('문형', 'Equisetum arvense', 18),
    ('물푸레나무', 'Fraxinus rhynchophylla', 18),
    ('미삼', 'Panax ginseng', 18),
    ('미후도', 'Actinidia arguta', 18),
    ('미후등', 'Actinidia arguta', 18),
    ('밀몽화', 'Buddleja officinalis', 18),
    ('바나바잎', 'Lagerstroemia speciosa', 18),
    ('박하', 'Mentha arvensis', 19),
    ('반대해', 'Sterculia scaphigera', 19),
    ('반묘', 'Mylabris cichorii', 19),
    ('반지련', 'Scutellaria barbata', 19),
    ('반하', 'Pinellia ternata', 19),
    ('방가지똥', 'Sonchus oleraceus', 19),
    ('방기', 'Sinomenium acutum', 19),
    ('방풍', 'Saposhnikovia divaricata', 19),
    ('백강잠', 'Bombyx mori', 19),
    ('백과', 'Ginkgo biloba', 19),
    ('백굴채', 'Chelidonium majus', 20),
    ('백급', 'Bletilla striata', 20),
    ('백단향', 'Santalum album', 20),
    ('백동백', 'Lindera glauca', 20),
    ('백두옹', 'Pulsatilla koreana', 20),
    ('백렴', 'Ampelopsis japonica', 20),
    ('백모근', 'Imperata cylindrica', 20),
    ('백미', 'Cynanchum atratum', 20),
    ('백복령', 'Poria cocos', 21),
    ('백부근', 'Stemona japonica', 21),
    ('백부자', 'Aconitum koreanum', 21),
    ('백선피', 'Dictamnus dasycarpus', 21),
    ('백수오', 'Cynanchum wilfordii', 21),
    ('백자인', 'Thuja orientalis', 21),
    ('백작약', 'Paeonia lactiflora', 21),
    ('백전', 'Cynanchum stauntoni', 21),
    ('백지', 'Angelica dahurica', 21),
    ('백질려', 'Tribulus terrestris', 21),
    ('백출', 'Atractylodes japonica', 22),
    ('백편두', 'Dolichos lablab', 22),
    ('백합', 'Lilium lancifolium', 22),
    ('백화사설초', 'Oldenlandia diffusa', 22),
    ('번백초', 'Potentilla discolor', 22),
    ('번서', 'Ipomoea batatas', 22),
    ('번석류엽', 'Psidium guajava', 22),
    ('번행', 'Tetragonia tetragonoides', 22),
    ('별갑', 'Amyda maakii', 22),
    ('별갑교', 'Amyda sinensis', 22),
    ('보골지', 'Psoralea corylifolia', 23),
    ('보두', 'Strychnos ignatii', 23),
    ('복령', 'Poria cocos', 23),
    ('복분자', 'Rubus coreanus', 23),
    ('복신', 'Poria cocos', 23),
    ('봉두근', 'Petasites japonicus', 23),
    ('봉두채', 'Petasites japonicus', 23),
    ('부소맥', 'Triticum aestivum', 23),
    ('부자', 'Aconitum carmichaeli', 23),
    ('부평', 'Spirodela polyrhiza', 23),
    ('비자', 'Torreya nucifera', 24),
    ('비파엽', 'Eriobotrya japonica', 24),
    ('비해', 'Dioscorea tokoro', 24),
    ('빈랑', 'Areca catechu', 24),
    ('빈랑자', 'Areca catechu', 24),
    ('사간', 'Belamcanda chinensis', 24),
    ('사과락', 'Luffa cylindrica', 24),
    ('사군자', 'Quisqualis indica', 24),
    ('사매', 'Duchesnea chrysantha', 24),
    ('사삼', 'Adenophora triphylla', 24),
    ('사원자', 'Astragalus complanatus', 25),
    ('사인', 'Amomum villosum', 25),
    ('사포도', 'Ampelopsis brevipedunculata', 25),
    ('사향초', 'Thymus quinquecostatus', 25),
    ('산내', 'Kaempferia galanga', 25),
    ('산두근', 'Sophora tonkinensis', 25),
    ('산모', 'Rumex acetosa', 25),
    ('산백국', 'Aster ageratoides', 25),
    ('산사', 'Crataegus pinnatifida', 25),
    ('산수유', 'Cornus officinalis', 26),
    ('산야완두', 'Vicia amoena', 26),
    ('산우', 'Ipomoea batatas', 26),
    ('산자고', 'Cremastra appendiculata', 26),
    ('산조인', 'Zizyphus jujuba', 26),
    ('산청목', 'Acer tegmentosum', 26),
    ('산초', 'Zanthoxylum piperitum', 26),
    ('산호초엽', 'Lindera glauca', 26),
    ('삼릉', 'Sparganium stoloniferum', 27),
    ('삼백초', 'Saururus chinensis', 27),
    ('상기생', 'Loranthus parasiticus', 27),
    ('상륙', 'Phytolacca esculenta', 27),
    ('상백피', 'Morus alba', 27),
    ('상산', 'Dichroa febrifuga', 27),
    ('상심자', 'Morus alba', 27),
    ('상엽', 'Morus alba', 27),
    ('상지', 'Morus alba', 27),
    ('상표초', 'Paratenodera sinensis', 27),
    ('상황', 'Phellinus linteus', 28),
    ('생강', 'Zingiber officinale', 28),
    ('생지황', 'Rehmannia glutinosa', 28),
    ('서목태', 'Glycine max', 28),
    ('서장경', 'Cynanchum paniculatum', 28),
    ('석결명', 'Haliotis gigantea', 28),
    ('석곡', 'Dendrobium nobile', 28),
    ('석남엽', 'Rhododendron brachycarpum', 28),
    ('석룡자', 'Eumeces chinensis', 28),
    ('석류', 'Punica granatum', 28),
    ('석위', 'Pyrrosia lingua', 29),
    ('석이', 'Umbilicaria esculenta', 29),
    ('석창포', 'Acorus gramineus', 29),
    ('선모', 'Curculigo orchioides', 29),
    ('선복화', 'Inula japonica', 29),
    ('선퇴', 'Cryptotympana pustulata', 29),
    ('선학초', 'Agrimonia pilosa', 29),
    ('설견초', 'Salvia plebeia', 29),
    ('섬서', 'Bufo bufo gargarizans', 29),
    ('섬수', 'Bufo bufo gargarizans', 30),
    ('세신', 'Asiasarum heterotropoides', 30),
    ('센나엽', 'Cassia angustifolia', 30),
    ('소계', 'Cephalonoplos segetum', 30),
    ('소목', 'Caesalpina sappan', 30),
    ('소백피', 'Ailanthus altissima', 30),
    ('소회향', 'Foeniculum vulgare', 30),
    ('속단', 'Dipsacus asperoides', 30),
    ('속수자', 'Euphorbia lathyris', 30),
    ('송엽', 'Pinus densiflora', 31),
    ('송절', 'Pinus densiflora', 31),
    ('송화분', 'Pinus densiflora', 31),
    ('쇄양', 'Cynomorium songaricum', 31),
    ('수국잎', 'Hydrangea macrophylla', 31),
    ('수랍목', 'Ligustrum obtusifolium', 31),
    ('수오등', 'Fallopia multiflora', 31),
    ('수우각', 'Bubalus bubalis', 31),
    ('숙지황', 'Rehmannia glutinosa', 31),
    ('스테비아', 'Stevia rebaudiana', 32),
    ('승마', 'Cimicifuga heracleifolia', 32),
    ('시라자', 'Anethum graveolens', 32),
    ('시체', 'Diospyros kaki', 32),
    ('시호', 'Bupleurum falcatum', 32),
    ('식방풍', 'Peucedanum japonicum', 32),
    ('신곡', 'Triticum aestivum', 32),
    ('신근초', 'Lycopodium clavatum', 32),
    ('신선초', 'Angelica keiskei', 32),
    ('신이', 'Magnolia denudata', 33),
    ('쑥부쟁이', 'Kalimeris yomena', 33),
    ('아마란스', 'Amaranthus caudatus', 33),
    ('아마인', 'Linum usitatissimum', 33),
    ('아불식초', 'Centipeda minima', 33),
    ('아삼', 'Anthriscus sylvestris', 33),
    ('아선약', 'Uncaria gambir', 33),
    ('아출', 'Curcuma zedoaria', 33),
    ('안식향', 'Styrax benzoin', 34),
    ('압척초', 'Commelina communis', 34),
    ('애엽', 'Artemisia argyi', 34),
    ('애호박', 'Cucurbita moschata', 34),
    ('앵도육', 'Prunus tomentosa', 34),
    ('야관문', 'Lespedeza cuneata', 34),
    ('야교등', 'Polygonum multiflorum', 34),
    ('야명사', 'Vespertilio superans', 34),
    ('야오동', 'Mallotus japonicus', 34),
    ('양괴', 'Maackia amurensis', 34),
    ('양유근', 'Codonopsis lanceolata', 35),
    ('양제근', 'Rumex japonicus', 35),
    ('어성초', 'Houttuynia cordata', 35),
    ('어성초근', 'Houttuynia cordata', 35),
    ('여로', 'Veratrum nigrum', 35),
    ('여정목', 'Ligustrum japonicum', 35),
    ('여정실', 'Ligustrum lucidum', 35),
    ('여정자', 'Ligustrum lucidum', 35),
    ('여지핵', 'Litchi chinensis', 35),
    ('연교', 'Forsythia viridissima', 35),
    ('연자육', 'Nelumbo nucifera', 36),
    ('연전초', 'Glechoma hederacea', 36),
    ('영릉향', 'Lysimachia foenum-graeci', 36),
    ('영신초', 'Polygola japonica', 36),
    ('영실', 'Rosa multiflora', 36),
    ('영실근', 'Rosa multiflora', 36),
    ('영양각', 'Gazella subgutturosa', 36),
    ('영지', 'Ganoderma lucidum', 36),
    ('예지자', 'Akebia quinata', 36),
    ('오가피', 'Acanthopanax sessiliflorus', 36),
    ('오공', 'Scolopendra subspinipes', 37),
    ('오령지', 'Trogopterus xanthipes', 37),
    ('오매', 'Prunus mume', 37),
    ('오미자', 'Schisandra chinensis', 37),
    ('오배자', 'Rhus javanica', 37),
    ('오수유', 'Evodia officinalis', 37),
    ('옥죽', 'Polygonatum odoratum', 37),
    ('옥촉서예', 'Zea mays', 37),
    ('와릉자', 'Tegillarca granosa', 37),
    ('와송', 'Orostachys japonicus', 38),
    ('왕불류행', 'Melandrium firmum', 38),
    ('용규', 'Solanum nigrum', 38),
    ('용뇌', 'Dryobalanops aromatica', 38),
    ('용담', 'Gentiana scabra', 38),
    ('용아초', 'Agrimonia pilosa', 38),
    ('용안육', 'Dimocarpus longan', 38),
    ('우담', 'Bos taurus domesticus', 38),
    ('우담남성', 'Arisaema amurense', 38),
    ('우두', 'Colocasia esculenta', 39),
    ('우방자', 'Arctium lappa', 39),
    ('우슬', 'Achyranthes japonica', 39),
    ('우절', 'Nelumbo nucifera', 39),
    ('운대자', 'Brassica chinensis', 39),
    ('운지', 'Trametes versicolor', 39),
    ('울금', 'Curcuma longa', 39),
    ('원지', 'Polygala tenuifolia', 39),
    ('원화', 'Daphne genkwa', 40),
    ('월견자', 'Oenothera odorata', 40),
    ('월계엽', 'Laurus nobilis', 40),
    ('위령선', 'Clematis mandshurica', 40),
    ('위릉채', 'Potentilla chinensis', 40),
    ('위유', 'Polygonatum odoratum', 40),
    ('유기노', 'Artemisia anomala', 40),
    ('유백피', 'Ulmus macrocarpa', 40),
    ('유지', 'Salix hallaisanensis', 40),
    ('유향', 'Boswellia carterii', 40),
    ('육계', 'Cinnamomum cassia', 41),
    ('육두구', 'Myristica fragrans', 41),
    ('육종용', 'Cistanche deserticola', 41),
    ('율초', 'Humulus japonicus', 41),
    ('은시호', 'Gypsophila oldhamiana', 41),
    ('은행엽', 'Ginkgo biloba', 41),
    ('음양곽', 'Epimedium koreanum', 41),
    ('의이인', 'Coix lacryma-jobi', 41),
    ('익모초', 'Leonurus sibiricus', 41),
    ('익지', 'Alpinia oxyphylla', 41),
    ('인동', 'Lonicera japonica', 42),
    ('인삼', 'Panax ginseng', 42),
    ('인삼화', 'Panax ginseng', 42),
    ('인진호', 'Artemisia capillaris', 42),
    ('일당귀', 'Angelica acutiloba', 42),
    ('자괴화', 'Acacia catechu', 42),
    ('자근', 'Lithospermum erythrorhizon', 42),
    ('자단향', 'Pterocarpus santalinus', 42),
    ('자소엽', 'Perilla frutescens', 43),
    ('자소자', 'Perilla frutescens', 43),
    ('자완', 'Aster tataricus', 43),
    ('자충', 'Eupolyphaga sinensis', 43),
    ('자화지정', 'Viola mandshurica', 43),
    ('작맥자', 'Avena sativa', 43),
    ('작약', 'Paeonia lactiflora', 43),
    ('잠사', 'Bombyx mori', 43),
    ('장뇌', 'Cinnamomum camphora', 43),
    ('장목', 'Cinnamomum camphora', 44),
    ('장미화', 'Rosa hybrida', 44),
    ('저두강', 'Oryza sativa', 44),
    ('저령', 'Polyporus umbellatus', 44),
    ('저마근', 'Boehmeria nivea', 44),
    ('저백피', 'Ailanthus altissima', 44),
    ('저실자', 'Broussonetia papyrifera', 44),
    ('적복령', 'Poria cocos', 44),
    ('적소두', 'Phaseolus angularis', 44),
    ('적양', 'Alnus japonica', 45),
    ('전갈', 'Buthus martensi', 45),
    ('전호', 'Peucedanum praeruptorum', 45),
    ('절패모', 'Fritillaria thunbergii', 45),
    ('정공등', 'Erycibe obtusifolia', 45),
    ('정력자', 'Lepidium apetalum', 45),
    ('정류', 'Tamarix juniperina', 45),
    ('정향', 'Syzygium aromaticum', 45),
    ('정향피', 'Syzygium aromaticum', 46),
    ('제니', 'Adenophora remotiflora', 46),
    ('제조', 'Holotrichia diomphalia', 46),
    ('조각자', 'Gleditsia officinalis', 46),
    ('조구등', 'Uncaria sinensis', 46),
    ('조협', 'Gleditsia japonica', 46),
    ('조휴', 'Paris polyphylla', 46),
    ('종대황', 'Rheum undulatum', 46),
    ('종려피', 'Trachycarpus fortunei', 46),
    ('죽력', 'Phyllostachys nigra', 47),
    ('죽여', 'Phyllostachys nigra', 47),
    ('죽엽', 'Phyllostachys nigra', 47),
    ('중국황금', 'Scutellaria baicalensis', 47),
    ('지골피', 'Lycium chinense', 47),
    ('지구목', 'Hovenia dulcis', 47),
    ('지구병', 'Hovenia dulcis', 47),
    ('지구자', 'Hovenia dulcis', 47),
    ('지금', 'Parthenocissus tricuspidata', 47),
    ('지마', 'Sesamum indicum', 48),
    ('지모', 'Anemarrhena asphodeloides', 48),
    ('지부자', 'Kochia scoparia', 48),
    ('지실', 'Poncirus trifoliata', 48),
    ('지유', 'Sanguisorba officinalis', 48),
    ('지황', 'Rehmannia glutinosa', 48),
    ('진교', 'Gentiana macrophylla', 48),
    ('진주', 'Pinctada martensii', 48),
    ('진피', 'Citrus unshiu', 48),
    ('질려자', 'Tribulus terrestris', 49),
    ('차가버섯', 'Inonotus Obliquus', 49),
    ('차전자', 'Plantago asiatica', 49),
    ('참가시나무', 'Quercus stenophylla', 49),
    ('창이자', 'Xanthium strumarium', 49),
    ('창출', 'Atractylodes lancea', 49),
    ('창포', 'Acorus calamus', 49),
    ('천궁', 'Cnidium officinale', 49),
    ('천남성', 'Arisaema amurense', 49),
    ('천련자', 'Melia azedarach', 50),
    ('천마', 'Gastrodia elata', 50),
    ('천문동', 'Asparagus cochinchinensis', 50),
    ('천산룡', 'Dioscorea septemloba', 50),
    ('천수근', 'Harpagophytum procumbens', 50),
    ('천오', 'Aconitum carmichaeli', 50),
    ('천초근', 'Rubia akane', 50),
    ('천축황', 'Phyllostachys bambusoides', 50),
    ('청대', 'Persicaria tinctoria', 50),
    ('청상자', 'Celosia argentea', 50),
    ('청피', 'Citrus unshiu', 51),
    ('청호', 'Artemisia apiacea', 51),
    ('초과', 'Amomum tsao-ko', 51),
    ('초두구', 'Alpinia katsumadai', 51),
    ('초목', 'Zanthoxylum piperitum', 51),
    ('초석잠근', 'Stachys riederi', 51),
    ('초오', 'Aconitum ciliare', 51),
    ('초호', 'Artemisia annua', 51),
    ('촉규근', 'Althaea rosea', 51),
    ('촉규화', 'Althaea rosea', 51),
    ('촉초', 'Zanthoxylum piperitum', 52),
    ('총백', 'Allium fistulosum', 52),
    ('측백엽', 'Thuja orientalis', 52),
    ('치자', 'Gardenia jasminoides', 52),
    ('칠엽담', 'Gynostemma pentaphyllum', 52),
    ('칠피', 'Rhus verniciflua', 52),
    ('칠해목', 'Ribes fasciculatum', 52),
    ('카카오닙스', 'Theobroma cacao', 52),
    ('콜라비', 'Brassica oleracea', 53),
    ('타임', 'Thymus quinquecostatus', 53),
    ('태자삼', 'Pseudostellaria heterophylla', 53),
    ('택란', 'Lycopus coreanus', 53),
    ('택사', 'Alisma orientale', 53),
    ('테프', 'Eragrostis tef', 53),
    ('토란줄기', 'Colocasia antiquorum', 53),
    ('토복령', 'Smilax china', 53),
    ('토사자', 'Cuscuta chinensis', 53),
    ('통내초', 'Euphorbia maculata', 54),
    ('통초', 'Tetrapanax papyriferus', 54),
    ('파극천', 'Morinda officinalis', 54),
    ('파두', 'Croton tiglium', 54),
    ('판람근', 'Isatis tinctoria', 54),
    ('팔각회향', 'Illicium verum', 54),
    ('패란', 'Eupatorium fortunei', 54),
    ('패장', 'Patrinia villosa', 54),
    ('패장근', 'Patrinia villosa', 54),
    ('페퍼민트', 'Mentha piperita', 54),
    ('편축', 'Polygonum aviculare', 55),
    ('포공영', 'Taraxacum platycarpum', 55),
    ('포도근', 'Vitis vinifera', 55),
    ('포황', 'Typha orientalis', 55),
    ('표고버섯', 'Lentinus edodes', 55),
    ('풍하이', 'Dendropanax morbiferus', 55),
    ('피나무', 'Tilia amurensis', 55),
    ('피마자', 'Ricinus communis', 55),
    ('필발', 'Piper longum', 55),
    ('필징가', 'Piper cubeba', 55),
    ('하고초', 'Prunella vulgaris', 56),
    ('하르파고피툼근', 'Harpagophytum procumbens', 56),
    ('하수오', 'Polygonum multiflorum', 56),
    ('하엽', 'Nelumbo nucifera', 56),
    ('학슬', 'Carpesium abrotanoides', 56),
    ('한국황금', 'Scutellaria baicalensis', 56),
    ('한련초', 'Eclipta prostrata', 56),
    ('한속단', 'Phlomis umbrosa', 56),
    ('한인진', 'Artemisia iwayomogi', 57),
    ('함초', 'Salicornia herbacea', 57),
    ('합개', 'Gekko gecko', 57),
    ('합환피', 'Albizzia julibrissin', 57),
    ('해금사', 'Lygodium japonicum', 57),
    ('해당근', 'Rosa rugosa', 57),
    ('해대', 'Laminaria japonica', 57),
    ('해동피', 'Kalopanax pictus', 57),
    ('해바라기대', 'Helianthus annuus', 57),
    ('해바라기씨', 'Helianthus annuus', 57),
    ('해방풍', 'Glehnia littoralis', 58),
    ('해백', 'Allium macrostemon', 58),
    ('해부석', 'Costazia aculeata', 58),
    ('해분', 'Notarchus leachii', 58),
    ('해삼', 'Stichopus japonicus', 58),
    ('해송자', 'Pinus koraiensis', 58),
    ('해파극', 'Morinda citrifolia', 58),
    ('해표초', 'Sepia esculenta', 58),
    ('해풍등', 'Piper kadsura', 58),
    ('행인', 'Prunus armeniaca', 59),
    ('향부자', 'Cyperus rotundus', 59),
    ('향유', 'Elsholtzia ciliata', 59),
    ('현삼', 'Scrophularia buergeriana', 59),
    ('현초', 'Geranium thunbergii', 59),
    ('현호색', 'Corydalis ternata', 59),
    ('혈갈', 'Daemonorops draco', 59),
    ('형개', 'Schizonepeta tenuifolia', 59),
    ('형조', 'Lespedeza bicolor', 59),
    ('호도', 'Juglans sinensis', 59),
    ('호로파', 'Trigonella foenum-graecum', 60),
    ('호장근', 'Polygonum cuspidatum', 60),
    ('호퇴자엽', 'Elaeagnus multiflora Thunb.', 60),
    ('호황련', 'Picrorhiza kurroa', 60),
    ('홍삼', 'Panax ginseng', 60),
    ('홍화', 'Carthamus tinctorius', 60),
    ('홍화자', 'Carthamus tinctorius', 60),
    ('화피', 'Betula platyphylla', 60),
    ('황금', 'Scutellaria baicalensis', 61),
    ('황기', 'Astragalus membranaceus', 61),
    ('황련', 'Coptis japonica', 61),
    ('황매목', 'Lindera obtusiloba', 61),
    ('황백', 'Phellodendron amurense', 61),
    ('황정', 'Polygonatum sibiricum', 61),
    ('황칠수엽', 'Dendropanax morbifera', 61),
    ('회향', 'Foeniculum vulgare', 61),
    ('후두고', 'Hericium erinaceum', 61),
    ('후추', 'Piper nigrum', 62),
    ('훤초근', 'Hemerocallis fulva', 62),
    ('흑메밀', 'Fagopyrum tartaricum', 62),
    ('흑미', 'Oryza sativa', 62),
    ('흑지마', 'Sesamum indicum', 62),
    ('희렴', 'Siegesbeckia pubescens', 62),
    ('흰목이', 'Tremella fuciformis', 62),
    ('히비스커스', 'Hibiscus', 62),
]


def _make_aliases() -> dict[str, dict]:
    aliases: dict[str, dict] = {}
    for name, reported, page in _NIKOM_FACTS:
        # Strip only an explicit author abbreviation; retain reported taxonomy.
        taxon = re.sub(r" [A-Z][a-z]+\.$", "", reported)
        words = taxon.split()
        taxon = " ".join([words[0], *[word.lower() for word in words[1:]]])
        url = _NIKOM_URL if page == 1 else f"{_NIKOM_URL}?viewPage={page}"
        if name not in aliases:
            aliases[name] = {
                "query": taxon, "taxa": [taxon], "reported_latin": reported,
                "mapping_source_url": url, "source_urls": [url],
                "scope": "reported_taxon" if len(words) > 1 else "broader_genus",
                "source_name": "한국한의약진흥원 한의약소재은행 공개 보유 한약재 색인",
                "license_label": _LICENSE,
            }
        else:
            if taxon not in aliases[name]["taxa"]:
                aliases[name]["taxa"].append(taxon)
            if url not in aliases[name]["source_urls"]:
                aliases[name]["source_urls"].append(url)
    # Independent primary sources retained separately for multiple origins.
    licorice_url = (
        "https://oasis.kiom.re.kr/oasis/herb/monoDetailView_M01.jsp"
        "?idx=7&keyword=&srch_menu_nix=&tab=1&work_seq=null"
    )
    aliases["감초"]["taxa"] = ["Glycyrrhiza uralensis", "Glycyrrhiza glabra", "Glycyrrhiza inflata"]
    aliases["감초"]["mapping_source_url"] = licorice_url
    aliases["감초"]["source_urls"].append(licorice_url)
    aliases["감초"]["source_name"] = "한국한의학연구원 OASIS 감초 기원 정보 / 한국한의약진흥원 공개 색인"
    coptis_url = "https://pmc.ncbi.nlm.nih.gov/articles/PMC8166882/"
    aliases["황련"]["taxa"].append("Coptis chinensis")
    aliases["황련"]["source_urls"].append(coptis_url)
    aliases["황련"]["source_name"] += " / Coptis chinensis 원논문"
    oasis_chart_url = "https://oasis.kiom.re.kr/oasis/herb/speciChartSearch.jsp?srch_menu_nix=LeoMYtGU"
    for name in ("황금", "강황", "지모"):
        aliases[name]["source_urls"].append(oasis_chart_url)
    for name, record in aliases.items():
        if len(record["taxa"]) > 1:
            genera = {taxon.split()[0] for taxon in record["taxa"]}
            if len(genera) == 1:
                record["query"] = next(iter(genera))
                record["scope"] = "broader_genus"
            else:
                record["query"] = name
                record["scope"] = "ambiguous_taxa"
        record["scope_note"] = (
            "여러 기원 또는 속 단위 표기 때문에 속 전체로 넓힌 검색입니다. 지정 기원 외 종도 포함할 수 있습니다."
            if record["scope"] == "broader_genus"
            else "공개 원천에 보고된 학명으로 검색합니다. 모든 공정서 기원이나 실제 한약재 성분을 검증한 목록은 아닙니다."
        )
    return aliases


HERB_ALIASES: dict[str, dict] = _make_aliases()


def resolve_herb_query(query: str) -> dict:
    """Expand only an exact Korean index name, preserving the supplied query."""
    if not isinstance(query, str):
        raise ValueError("query must be a string")
    name = unicodedata.normalize("NFC", query).strip()
    record = HERB_ALIASES.get(name)
    if record is None:
        return {
            "query": query, "original_query": query, "mapping_source_url": None,
            "scope": "unmapped", "mapped": False, "taxa": [], "license_label": None,
        }
    return {
        **deepcopy(record), "original_query": query,
        "mapped": record["scope"] != "ambiguous_taxa", "korean_name": name,
    }


def list_herb_aliases() -> list[dict]:
    """Return reference metadata without exposing mutable module state."""
    return [{"name": name, **deepcopy(record)} for name, record in sorted(HERB_ALIASES.items())]
