"""Round-1 editorial changes. Frozen observations are not edited."""
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT/'research/manuscript'
BASE=SRC/'round1/frozen_round0/research/manuscript'

def replace(text, old, new):
    assert old in text, old[:120]
    return text.replace(old,new)

def main():
    m=(BASE/'manuscript.md').read_text()
    m=replace(m,'# Auditable medicinal-plant discovery', '# HerbFold links medicinal-plant discovery')
    m=m.replace('HerbFold links medicinal-plant discovery links chemical provenance','HerbFold links chemical provenance')
    # Preserve the corresponding-author edit present in the latest supplied DOCX.
    m=re.sub(r'^Correspondence: .*$', 'Correspondence: Young Sahng Suh, MPH (PhD candidate); Department of AI and Data Science, aSSIST University (Seoul School of Integrated Sciences & Technologies)/The Machina AI, 46 Ewhayeodae 2-gil, Seodaemun-gu, Seoul 03767, Republic of Korea.', m, flags=re.M)
    m=replace(m,'with topological polar', 'with topological polar') if 'with topological polar' in m else m
    m=m.replace('median topological polar surface areas', 'median topological polar surface areas (TPSA; the polar-atom surface contribution)')
    m=m.replace('suggests useful starting diversity', 'describes chemical diversity relative to this reference')
    m=m.replace('supports a useful computational statement','supports a defined computational statement')
    m=m.replace('The medicinal-plant specialization becomes useful when','The medicinal-plant specialization preserves distinctions when')
    m=m.replace('a species assignment.','a species assignment.')
    m=m.replace('For top-ranked outputs, aspirin pTM increased', 'Predicted template-modelling score (pTM) summarizes confidence in global relative placement; interface pTM (ipTM) focuses on inter-chain placement. Predicted local distance difference test (pLDDT) is a 0–100 local structural-confidence score. None is an affinity estimate. For top-ranked outputs, aspirin pTM increased')
    m=m.replace('joint inclusion of MSA and templates','joint inclusion of multiple sequence alignments (MSAs; aligned homologous sequences) and structural templates',1)
    # The source first names the joint condition in Results with a different phrase.
    first=m.find('## Results')
    tail=m[first:]
    pos=tail.find('MSA')
    if pos>=0 and 'multiple sequence alignments' not in tail[:pos+80]:
        tail=tail[:pos]+'multiple sequence alignment (MSA; aligned homologous sequences)'+tail[pos+3:]
        m=m[:first]+tail
    m=m.replace('human COX-2, joint','human cyclooxygenase-2 (COX-2), joint',1)
    m=m.replace('human PTGS2','human cyclooxygenase-2 (COX-2; encoded by PTGS2)',1)
    m=m.replace('two BRICS candidates, quercetin and aspirin, represented by molecular weight/650, logP/6, TPSA/180 and QED.', 'two candidates generated by breaking of retrosynthetically interesting chemical substructures (BRICS), quercetin and aspirin. Inputs were molecular weight/650, logP/6 (a lipophilicity descriptor), TPSA/180 and the quantitative estimate of drug-likeness (QED; a physicochemical desirability score).')
    m=m.replace('with an RBF scale fixed at one', 'with a radial basis function (RBF) scale fixed at one',1)
    m=m.replace('One KCNH2 assay supported', 'One assay for the human ether-à-go-go-related gene potassium channel (hERG; encoded by KCNH2) supported',1)
    m=m.replace('Random-forest MAE was 0.46265 pIC50 units on 24 held-out structures and 0.42243 among 23 in-domain test structures.', 'Random-forest mean absolute error (MAE) was 0.46 pIC50 units on 24 held-out structures and 0.42 among 23 in-domain test structures. Here pIC50 is minus the base-10 logarithm of the molar half-maximal inhibitory concentration.')
    m=m.replace('ROC-AUC ranged from', 'area under the receiver-operating-characteristic curve (ROC-AUC) ranged from',1)
    m=m.replace('PAINS or Brenk alerts','pan-assay interference compound (PAINS) or Brenk structural alerts',1)
    m=m.replace('Together, they ask where', 'Together, they ask where')
    m=m.replace('(Table 1).', '(Supplementary Table S13).')
    m=m.replace('These are software-behaviour checks, not biological replicates.', 'Table 1 connects each implemented constraint to its validator and evidence record. These are software-behaviour checks, not biological replicates.')
    m=m.replace('A 500-record reconstruction check supplements complete row-count, uniqueness and lineage audits.', 'The reconstruction check selects the first 500 retained rows ordered by full structure SHA-256, without random sampling. Recombination of the recorded parent fragments must reproduce the stored canonical isomeric SMILES and its SHA-256; the archived check passed all 500. This checks reconstruction in a deterministic subset, while row-count, uniqueness and stored lineage conditions use all 3,701,740 retained rows. The retained large database is required to repeat the full-table audit.')
    m=m.replace('For exposition, a result is represented as e = (k, c, q, v, u, p, d), where k identifies', 'For exposition, a result is represented as\n\n{{EQUATION:1|e = (k, c, q, v, u, p, d)}}\n\nHere k identifies')
    m=m.replace('With Q qubits, the distance and kernel are D_ij = sum_q ||r_iq - r_jq||^2/(2Q) and K_ij = exp(-gamma D_ij), with gamma fixed at one before acquisition.', 'With Q measured qubits, the distance and kernel are\n\n{{EQUATION:2|Dᵢⱼ = (1 / 2Q) ∑q ‖rᵢq − rⱼq‖²,    Kᵢⱼ = exp(−γDᵢⱼ).}}\n\nIndices i and j identify the ordered input rows; q indexes the measured qubits; γ is the dimensionless bandwidth parameter, fixed at one in the archived acquisition configuration.')
    m=m.replace('Centering uses Kc = HKH, where H = I - 11ᵀ/n. Alignment is the Frobenius inner product of two centered matrices divided by the product of their Frobenius norms', 'Centering and alignment use\n\n{{EQUATION:3|Kc = HKH,    H = I − 11ᵀ/n,    A(K,L) = ⟨Kc,Lc⟩F / (‖Kc‖F ‖Lc‖F).}}\n\nHere n is the number of inputs, I is the identity matrix, 1 is the all-ones column vector, L is the reference kernel and F denotes the Frobenius inner product or norm')
    m=m.replace('Entropy effective rank is exp(-sum_j p_j log p_j), with p_j obtained by normalizing the positive eigenvalues', 'Entropy effective rank is\n\n{{EQUATION:4|rₑff = exp(−∑j pⱼ log pⱼ),    pⱼ = λⱼ / ∑k λk.}}\n\nThe λ values are the retained positive eigenvalues; p is their normalized distribution')
    m=m.replace('in 64 deterministic bootstrap replicates.', 'in 64 bootstrap replicates using seed 42. Bounds are the 2.5th and 97.5th percentiles with NumPy linear interpolation (index (B−1)p). With B = 64, these correspond to fractional indices 1.575 and 61.425; tail resolution is coarse. The original ranges are retained without claiming calibrated confidence coverage.')
    m=m.replace('### Statistical interpretation and reproducibility', '### AI-assisted manuscript and analysis preparation\n\nOpenAI Codex assistance was used for manuscript drafting and revision, primary-source retrieval, Python analysis and test scripts, deterministic data plotting, document layout and computational checks. Parallel coding/research assistants helped inspect source records and executable constraints. No generated image was used to represent a measurement. These uses exceed copy editing and are disclosed here under the journal policy. The present revision adds CPU calculations on archived observations, without a new AF3 or IBM acquisition. Human authors must verify the science, citations, tool-assisted calculations and final submission; this statement does not assert that all-author approval has already occurred.\n\n### Statistical interpretation and reproducibility')
    m=m.replace('This study received no dedicated external funding, as declared in the author-supplied HANBIT manuscript. Computational resources used for the present analyses are documented in the execution records and evidence ledger.', 'Study-specific funding confirmation is pending author approval. The supplied HANBIT source reports no dedicated external funding; that statement has not been independently confirmed for the present HerbFold study. Computational resource use is documented in the execution records. The corresponding author must confirm funders, grant identifiers and any relevant institutional or commercial support before submission.')
    m=m.replace("The author-supplied declaration reports no competing interests. Young Sahng Suh's position as CEO of The Machina AI is disclosed in the author information.", "Young Sahng Suh's recorded role as CEO of The Machina AI is disclosed. Each author's study-specific financial and non-financial competing interests remain to be confirmed; the no-conflict statement in the source manuscript is not treated as approval for this study.")
    m=m.replace('### AI-assisted preparation\n\nAI assistance covered drafting, coding, data analysis, figures and formatting, with numerical and visual checks. The named authors retain responsibility for reviewing and submitting this manuscript.', '### Manuscript approval\n\nFinal approval by every named author has not been supplied. This revision is a review draft pending study-specific contribution, funding, competing-interest and approval confirmations; it is not represented as administratively ready for submission.')
    m=m.replace('8 September 2026. We used', '8 September 2026, with a separately versioned reporting and CPU-audit revision on 9 September 2026. We used')
    (SRC/'manuscript.md').write_text(m)
    s=(BASE/'supplementary.md').read_text()
    s=s.replace('deterministic 500-structure hash sample','deterministic first 500 retained structures in ascending full-SHA-256 order (not a random sample)')
    s=s.replace('M1','C1').replace('M3','Q')
    s=s.replace('## 국문 연구 요약', '## 국문 연구 요약')
    (SRC/'supplementary.md').write_text(s)
    print('Base editorial revision written; numerical insertions are integrated separately.')

if __name__=='__main__':main()
